import test from 'node:test';
import assert from 'node:assert/strict';
import {JAB_BODY,LEFT_BLOCK_TURN,MOVES,STEP,TARGET_HEIGHT,gloveLocal,leftBlockMotion} from './core.mjs';
import {LAB_CASES,advanceLabRun,createLabRun,runLabToCompletion} from './scenario-lab.mjs';

test('The lab presents jab defenses as separate ordered cases',()=>{
  assert.equal(LAB_CASES.length,3);
  assert.deepEqual(LAB_CASES.map(item=>item.id),['jab-right-parry','jab-right-block','jab-left-block']);
  assert.deepEqual(LAB_CASES.map(item=>item.number),['01','02','03']);
});

test('Case 01 proves the lower face target, continuous guard motion, synchronized foot and body work, and the 80% parry',()=>{
  const run=runLabToCompletion(0);
  assert.equal(run.status,'complete');
  assert.equal(run.impact.event.defense,'parry');
  assert.ok(run.impact.event.punchProgress>=.80&&run.impact.event.punchProgress<=.825);
  assert.equal(run.impact.attackerLeftDeflection>3.8,true);
  assert.equal(run.impact.defenderRightDeflection,0);
  assert.equal(run.impact.defenderRightParry,'tap');
  assert.ok(run.impact.attackerLeftGlove[1]<=TARGET_HEIGHT.head-.06);
  assert.ok(run.defenseIssuedAt>MOVES.jab.cue+.45&&run.defenseIssuedAt<MOVES.jab.cue+.5,'wait for the jab to approach before starting the right parry');
  assert.ok(run.preCueMotion.samples>=120);
  assert.ok(run.preCueMotion.L.range>=.02&&run.preCueMotion.R.range>=.02);
  assert.equal(run.punchStartAt,run.leadFootStartAt);
  assert.equal(run.punchStartAt,run.bodyStartAt);
  assert.ok(run.leadFootPeak>=.075);
  assert.ok(run.bodyPeak.hip>=JAB_BODY.hipForward*.75);
  assert.ok(run.bodyPeak.chest>=JAB_BODY.chestForward*.75);
  assert.ok(run.bodyPeak.head>=JAB_BODY.headForward*.75);
  assert.ok(run.bodyPeak.turn>=JAB_BODY.turn*.75);
  assert.ok(run.impact.attackerBody.progress>=.75);
  assert.ok(run.impact.attackerLeadFoot.forward>=.075&&run.impact.attackerLeadFoot.forward<=.09);
  assert.ok(run.impact.attackerLeadFoot.lift>0);
  assert.ok(Math.abs(run.parryStart[0]-run.impact.defenderRightGlove[0])<.01);
  assert.ok(run.tapStart[1]-run.impact.defenderRightGlove[1]>=.04);
  assert.ok(run.rebound.forward>=.12);
  assert.ok(run.rebound.downward>=.16);
  assert.equal(run.checks.length,9);
  assert.equal(run.checks.every(check=>check.pass),true);
});

test('Case 02 proves a right block absorbs the jab without deflecting either arm',()=>{
  const run=runLabToCompletion(1);
  assert.equal(run.status,'complete');
  assert.equal(run.impact.event.defense,'block');
  assert.equal(run.impact.event.damage,1);
  assert.equal(run.impact.attackerLeftDeflection,0);
  assert.equal(run.impact.defenderRightDeflection,0);
  assert.equal(run.checks.length,5);
  assert.equal(run.checks.every(check=>check.pass),true);
});

test('Case 03 catches the jab at the left glove and sends it to screen right outside the head',()=>{
  const run=createLabRun(2),player=run.state.fighters[0];
  const startLeft=gloveLocal(player,'L').slice(),startRight=gloveLocal(player,'R').slice();
  while(run.state.time<2.5)advanceLabRun(run,STEP);
  const midLeft=gloveLocal(player,'L'),midRight=gloveLocal(player,'R');
  assert.ok(midLeft[1]>startLeft[1]+.2&&midLeft[1]<startLeft[1]+.5);
  assert.equal(midRight[1],startRight[1]);
  assert.ok(leftBlockMotion(player).turn<0);
  while(!run.impact)advanceLabRun(run,STEP);
  const contactPose=gloveLocal(run.state.fighters[1],'L');
  assert.deepEqual(contactPose,run.impact.event.redirectFrom,'the visual trajectory begins at the actual glove contact');
  advanceLabRun(run,STEP);
  const nextPose=gloveLocal(run.state.fighters[1],'L');
  assert.ok(nextPose[0]>contactPose[0]&&nextPose[2]>contactPose[2],'the jab moves right and forward immediately after contact');
  while(run.status==='running')advanceLabRun(run,STEP);
  assert.equal(run.status,'complete');
  assert.ok(run.leftBlockIssuedAt>=.75&&run.leftBlockIssuedAt<.75+STEP);
  assert.ok(run.leftBlockMidpointY>startLeft[1]+.2&&run.leftBlockMidpointY<run.impact.defenderLeftGlove[1]-.2);
  assert.ok(run.impact.defenderLeftGlove[1]>startLeft[1]+.5);
  assert.equal(run.impact.defenderRightGlove[1],startRight[1]);
  assert.ok(run.impact.defenderRightGlove[0]<startRight[0],'the body turn carries the right glove outward while it stays low');
  assert.ok(run.impact.defenderTurn.turn<=-LEFT_BLOCK_TURN.angle*.9);
  assert.ok(run.impact.defenderLeftGlove[0]<=.10,'the left glove comes toward the center line');
  assert.equal(run.impact.defenderLeftDefense,'block');
  assert.equal(run.impact.defenderRightDefense,'body');
  assert.equal(run.impact.event.type,'block');
  assert.equal(run.impact.event.technique,'left-turn');
  assert.equal(run.impact.event.blockSide,'L');
  assert.ok(run.impact.event.punchProgress<.75,'the first contact happens before full extension');
  assert.ok(run.impact.event.gloveDistance<=LEFT_BLOCK_TURN.contactDistance);
  assert.equal(run.impact.event.damage,0);
  assert.equal(run.impact.playerHp,100);
  assert.ok(run.redirectPeak>=LEFT_BLOCK_TURN.jabRedirect*.95);
  assert.ok(run.redirectForwardPeak>=LEFT_BLOCK_TURN.redirectForward*.95);
  assert.ok(run.headClearanceMin>1,'the redirected glove stays outside the head hit region');
  assert.equal(run.impact.attackerLeftDeflection,0);
  assert.equal(run.impact.defenderLeftDeflection,0);
  assert.equal(run.impact.defenderRightDeflection,0);
  assert.equal(run.checks.length,5);
  assert.equal(run.checks.every(check=>check.pass),true);
});
