import test from 'node:test';
import assert from 'node:assert/strict';
import {JAB_BODY,LEFT_BLOCK_TURN,MOVES,STEP,TARGET_HEIGHT,gloveLocal,leftBlockMotion,leadFootMotion,jabBodyMotion,observeOpponent} from './core.mjs';
import {LAB_CASES,advanceLabRun,createLabRun,runLabToCompletion} from './scenario-lab.mjs';

test('The lab presents jab defenses as separate ordered cases',()=>{
  assert.equal(LAB_CASES.length,4);
  assert.deepEqual(LAB_CASES.map(item=>item.id),['jab-right-parry','jab-right-block','jab-left-block','jab-left-parry']);
  assert.deepEqual(LAB_CASES.map(item=>item.number),['01','02','03','04']);
});

test('Case 01 proves the lower face target, continuous guard motion, synchronized foot and body work, and the 80% parry',()=>{
  const run=runLabToCompletion(0);
  assert.equal(run.status,'complete');
  assert.equal(run.impact.event.defense,'parry');
  assert.ok(run.impact.event.punchProgress>=.80&&run.impact.event.punchProgress<=.825);
  assert.equal(run.impact.attackerLeftDeflection>3.8,true);
  assert.equal(run.impact.defenderRightDeflection,0);
  assert.equal(run.impact.defenderRightParry,'tap');
  assert.ok(run.impact.attackerLeftGlove[1]<=TARGET_HEIGHT.head-.06);
  assert.ok(run.defenseIssuedAt>MOVES.jab.cue+.45&&run.defenseIssuedAt<MOVES.jab.cue+.5,'wait for the jab to approach before starting the right parry');
  assert.ok(run.preCueMotion.samples>=120);
  assert.ok(run.preCueMotion.L.range>=.02&&run.preCueMotion.R.range>=.02);
  assert.equal(run.punchStartAt,run.leadFootStartAt);
  assert.equal(run.punchStartAt,run.bodyStartAt);
  assert.ok(run.leadFootPeak>=.075);
  assert.ok(run.bodyPeak.hip>=JAB_BODY.hipForward*.75);
  assert.ok(run.bodyPeak.chest>=JAB_BODY.chestForward*.75);
  assert.ok(run.bodyPeak.head>=JAB_BODY.headForward*.75);
  assert.ok(run.bodyPeak.turn>=JAB_BODY.turn*.75);
  assert.ok(run.impact.attackerBody.progress>=.75);
  assert.ok(run.impact.attackerLeadFoot.forward>=.075&&run.impact.attackerLeadFoot.forward<=.09);
  assert.ok(run.impact.attackerLeadFoot.lift>0);
  assert.ok(Math.abs(run.parryStart[0]-run.impact.defenderRightGlove[0])<.01);
  assert.ok(run.tapStart[1]-run.impact.defenderRightGlove[1]>=.04);
  assert.ok(run.rebound.forward>=.12);
  assert.ok(run.rebound.downward>=.16);
  assert.equal(run.checks.length,9);
  assert.equal(run.checks.every(check=>check.pass),true);
});

test('Case 02 proves a right block absorbs the jab without deflecting either arm',()=>{
  const run=runLabToCompletion(1);
  assert.equal(run.status,'complete');
  assert.equal(run.impact.event.defense,'block');
  assert.equal(run.impact.event.damage,1);
  assert.equal(run.impact.attackerLeftDeflection,0);
  assert.equal(run.impact.defenderRightDeflection,0);
  assert.equal(run.checks.length,5);
  assert.equal(run.checks.every(check=>check.pass),true);
});

test('Case 03 places the left glove on the jab line, holds contact briefly, then returns along the incoming path',()=>{
  const run=createLabRun(2),player=run.state.fighters[0];
  const startLeft=gloveLocal(player,'L').slice(),startRight=gloveLocal(player,'R').slice();
  while(run.state.time<2.5)advanceLabRun(run,STEP);
  const midLeft=gloveLocal(player,'L'),midRight=gloveLocal(player,'R');
  assert.ok(midLeft[1]>startLeft[1]+.2&&midLeft[1]<startLeft[1]+.5);
  assert.ok(midRight[1]>startRight[1]+.2,'the right glove also rises to the forehead');
  assert.ok(leftBlockMotion(player).turn<0);
  while(!run.impact)advanceLabRun(run,STEP);
  const attacker=run.state.fighters[1],contactPose=gloveLocal(attacker,'L'),contactFoot=leadFootMotion(attacker),contactBody=jabBodyMotion(attacker);
  assert.deepEqual(contactPose,run.impact.event.blockedFrom,'the punch stops where it touches the glove');
  assert.equal(observeOpponent(run.state,0).action.phase,'return','a blocked jab is no longer an incoming windup');
  advanceLabRun(run,STEP);
  assert.deepEqual(gloveLocal(attacker,'L'),contactPose,'the punch must not pass through or slide sideways');
  assert.equal(leadFootMotion(attacker).forward,contactFoot.forward);
  assert.equal(jabBodyMotion(attacker).hipForward,contactBody.hipForward);
  while(attacker.attack?.blocked&&attacker.attack.t<attacker.attack.blocked.startT+LEFT_BLOCK_TURN.hold+STEP)advanceLabRun(run,STEP);
  assert.ok(gloveLocal(attacker,'L')[2]<contactPose[2],'the fist retreats after the brief stop');
  assert.ok(leadFootMotion(attacker).forward<contactFoot.forward,'the lead foot retreats with the fist');
  assert.ok(jabBodyMotion(attacker).hipForward<contactBody.hipForward,'the hip retreats with the fist');
  while(run.status==='running')advanceLabRun(run,STEP);
  assert.equal(run.status,'complete');
  assert.ok(run.leftBlockIssuedAt>=.75&&run.leftBlockIssuedAt<.75+STEP);
  assert.ok(run.leftBlockMidpointY>startLeft[1]+.2&&run.leftBlockMidpointY<run.impact.defenderLeftGlove[1]-.15);
  assert.ok(run.impact.defenderLeftGlove[1]>startLeft[1]+.4);
  assert.ok(run.impact.defenderRightGlove[1]>startRight[1]+.4,'the right glove stays beside the forehead');
  assert.ok(Math.abs(run.impact.defenderLeftGlove[2]-run.impact.defenderRightGlove[2])<.01,'both gloves stay at the same forehead depth');
  assert.ok(run.impact.defenderTurn.turn<=-LEFT_BLOCK_TURN.angle*.9);
  assert.ok(run.impact.defenderLeftGlove[0]<.05,'the left glove comes to the jab line');
  assert.equal(run.impact.defenderLeftDefense,'block');
  assert.equal(run.impact.defenderRightDefense,'block');
  assert.equal(run.impact.event.type,'block');
  assert.equal(run.impact.event.technique,'left-turn');
  assert.equal(run.impact.event.blockSide,'L');
  assert.ok(run.impact.event.punchProgress<.95,'the first contact happens before full extension');
  assert.ok(run.impact.event.gloveDistance<=LEFT_BLOCK_TURN.bothHeadContactDistance);
  assert.ok(run.impact.event.lineOffset<LEFT_BLOCK_TURN.lineOffset,'the glove surface intersects the jab line');
  assert.equal(run.impact.event.damage,0);
  assert.equal(run.impact.playerHp,100);
  assert.ok(run.holdSamples>=10&&run.holdMaxMotion<1e-7);
  assert.ok(run.forwardAfterBlockMax<1e-7,'the fist never moves farther through the block');
  assert.ok(run.returnPathError<1e-6&&run.retreatDistance>.4,'the fist goes back along its incoming line');
  assert.equal(run.impact.attackerLeftDeflection,0);
  assert.equal(run.impact.defenderLeftDeflection,0);
  assert.equal(run.impact.defenderRightDeflection,0);
  assert.equal(run.checks.length,5);
  assert.equal(run.checks.every(check=>check.pass),true);
});

test('Case 04 catches the visible jab with the left hand and redirects it right while the arm is unavailable',()=>{
  const run=createLabRun(3),player=run.state.fighters[0];
  assert.equal(player.leftTurnGuard,'both-head');
  while(!run.impact)advanceLabRun(run,STEP);
  const impact=run.impact,contactGlove=gloveLocal(run.state.fighters[1],'L').slice();
  assert.equal(impact.event.technique,'left-cross');
  assert.equal(impact.event.parrySide,'L');
  assert.ok(impact.event.punchProgress>=.80&&impact.event.punchProgress<=.825);
  assert.ok(impact.event.gloveDistance<=.14);
  assert.ok(impact.defenderLeftGlove[2]>run.parryStart[2]+.10,'the parrying left glove reaches farther forward before contact');
  assert.equal(impact.event.damage,0);
  assert.equal(impact.playerHp,100);
  assert.ok(impact.attackerLeftDeflection>3.8);
  assert.equal(impact.defenderLeftDeflection,0);
  while(!run.rebound)advanceLabRun(run,STEP);
  const turnedGlove=gloveLocal(run.state.fighters[1],'L');
  assert.ok(turnedGlove[0]>contactGlove[0]+.19&&turnedGlove[0]<contactGlove[0]+.23,'the jab moves about 21 cm to the viewer right');
  assert.ok(turnedGlove[2]>contactGlove[2]+.12,'the jab keeps moving toward the player');
  assert.ok(turnedGlove[1]<contactGlove[1]-.04,'the top tap lowers the jab slightly');
  while(run.status==='running')advanceLabRun(run,STEP);
  assert.ok(run.rightClearanceMin>=.26,'the redirected jab stays clear of the unused right glove');
  assert.equal(run.checks.length,5);
  assert.equal(run.checks.every(check=>check.pass),true);
});
